<?php

namespace ContainerH9Xxq6s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_CuYV_XgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.cuYV.Xg' shared service.
     *
     * @return \Entity\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\PostController::read()": the $post argument is type-hinted with the non-existent class or interface: "Entity\\Post".');
    }
}
