<?php

namespace ContainerH9Xxq6s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L649L_CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L649L.c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L649L.c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', '.errored.cuYV.Xg', NULL, 'Cannot determine controller argument for "App\\Controller\\PostController::read()": the $post argument is type-hinted with the non-existent class or interface: "Entity\\Post".'],
        ], [
            'post' => '?',
        ]);
    }
}
