<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2MOxEIs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2MOxEIs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2MOxEIs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2MOxEIs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2MOxEIs\App_KernelDevDebugContainer([
    'container.build_hash' => '2MOxEIs',
    'container.build_id' => '4aca4a62',
    'container.build_time' => 1639842103,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2MOxEIs');
